name: Run Telegram Bot

on:
  # Event 'push' akan memicu workflow setiap kali ada push ke branch 'main'
  # Ini cocok untuk deployment otomatis setelah Anda melakukan perubahan kode.
  push:
    branches:
      - main
  # Event 'workflow_dispatch' memungkinkan Anda menjalankan workflow secara manual dari UI GitHub Actions.
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest # Menggunakan runner Ubuntu terbaru

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 # Mengunduh kode dari repositori Anda

    - name: Set up Python
      uses: actions/setup-python@v5 # Mengatur lingkungan Python
      with:
        python-version: '3.10' # Sesuaikan dengan versi Python yang Anda gunakan

    - name: Install dependencies
      run: pip install -r requirements.txt # Menginstal pustaka dari requirements.txt

    - name: Run Telegram Bot
      # Menyediakan token bot sebagai variabel lingkungan untuk skrip Python
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      run: python bot.py # Menjalankan skrip bot utama Anda
